server:
  port: 9001

spring:
  application:
    name: house-data-process-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  queuenames:
    name: q_san_francisco_county
  cloud:
    stream:
      bindings:
        output: updated_houses
